# Generated by Django 4.2.2 on 2023-06-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facts", "0003_animalfact_name_capitalfact_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animalfact",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="capitalfact",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
