# Generated by Django 4.2.2 on 2023-06-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facts", "0004_alter_animalfact_name_alter_capitalfact_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="capitalfact",
            name="state",
            field=models.CharField(default="N/A", max_length=200),
        ),
    ]
