# Generated by Django 4.2.2 on 2023-06-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facts", "0005_capitalfact_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capitalfact",
            name="state",
            field=models.CharField(max_length=200),
        ),
    ]
